// <auto-generated />
using System;
using Ecommerce.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302055029_UpdateProductImagePath")]
    partial class UpdateProductImagePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.API.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Điện thoại"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phụ kiện"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Đồng hồ thông minh"
                        });
                });

            modelBuilder.Entity("Ecommerce.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Mô tả chi tiết sản phẩm iPhone 15 Pro Max. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4742),
                            Name = "iPhone 15 Pro Max",
                            OriginalPrice = 35060000m
                        },
                        new
                        {
                            Id = 2,
                            Content = "Mô tả chi tiết sản phẩm Samsung Galaxy S24 Ultra. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4755),
                            Name = "Samsung Galaxy S24 Ultra",
                            OriginalPrice = 10640000m,
                            SalePrice = 9044000.00m
                        },
                        new
                        {
                            Id = 3,
                            Content = "Mô tả chi tiết sản phẩm Xiaomi 14 Pro. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4757),
                            Name = "Xiaomi 14 Pro",
                            OriginalPrice = 12570000m
                        },
                        new
                        {
                            Id = 4,
                            Content = "Mô tả chi tiết sản phẩm MacBook Air M3. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4760),
                            ImagePath = "/uploads/MacBook-Air-M3-6.jpg",
                            Name = "MacBook Air M3",
                            OriginalPrice = 37590000m,
                            SalePrice = 31951500.00m
                        },
                        new
                        {
                            Id = 5,
                            Content = "Mô tả chi tiết sản phẩm Dell XPS 15. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4763),
                            Name = "Dell XPS 15",
                            OriginalPrice = 12810000m,
                            SalePrice = 10888500.00m
                        },
                        new
                        {
                            Id = 6,
                            Content = "Mô tả chi tiết sản phẩm Asus Zenbook 14. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4766),
                            Name = "Asus Zenbook 14",
                            OriginalPrice = 15550000m
                        },
                        new
                        {
                            Id = 7,
                            Content = "Mô tả chi tiết sản phẩm AirPods Pro 2. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4768),
                            Name = "AirPods Pro 2",
                            OriginalPrice = 27750000m
                        },
                        new
                        {
                            Id = 8,
                            Content = "Mô tả chi tiết sản phẩm Samsung Galaxy Buds 3. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4771),
                            Name = "Samsung Galaxy Buds 3",
                            OriginalPrice = 22140000m
                        },
                        new
                        {
                            Id = 9,
                            Content = "Mô tả chi tiết sản phẩm Logitech MX Master 3S. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4773),
                            Name = "Logitech MX Master 3S",
                            OriginalPrice = 28280000m
                        },
                        new
                        {
                            Id = 10,
                            Content = "Mô tả chi tiết sản phẩm iPad Pro M4. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4776),
                            Name = "iPad Pro M4",
                            OriginalPrice = 41630000m,
                            SalePrice = 35385500.00m
                        },
                        new
                        {
                            Id = 11,
                            Content = "Mô tả chi tiết sản phẩm Samsung Galaxy Tab S9. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4778),
                            Name = "Samsung Galaxy Tab S9",
                            OriginalPrice = 22880000m
                        },
                        new
                        {
                            Id = 12,
                            Content = "Mô tả chi tiết sản phẩm Xiaomi Pad 6. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4781),
                            Name = "Xiaomi Pad 6",
                            OriginalPrice = 9050000m,
                            SalePrice = 7692500.00m
                        },
                        new
                        {
                            Id = 13,
                            Content = "Mô tả chi tiết sản phẩm Apple Watch Series 9. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4813),
                            Name = "Apple Watch Series 9",
                            OriginalPrice = 41720000m,
                            SalePrice = 35462000.00m
                        },
                        new
                        {
                            Id = 14,
                            Content = "Mô tả chi tiết sản phẩm Samsung Galaxy Watch 6. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4816),
                            Name = "Samsung Galaxy Watch 6",
                            OriginalPrice = 6980000m,
                            SalePrice = 5933000.00m
                        },
                        new
                        {
                            Id = 15,
                            Content = "Mô tả chi tiết sản phẩm Garmin Venu 3. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4818),
                            Name = "Garmin Venu 3",
                            OriginalPrice = 11640000m,
                            SalePrice = 9894000.00m
                        },
                        new
                        {
                            Id = 16,
                            Content = "Mô tả chi tiết sản phẩm Sony WH-1000XM5. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4821),
                            Name = "Sony WH-1000XM5",
                            OriginalPrice = 36160000m,
                            SalePrice = 30736000.00m
                        },
                        new
                        {
                            Id = 17,
                            Content = "Mô tả chi tiết sản phẩm Anker PowerBank 20K. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4823),
                            Name = "Anker PowerBank 20K",
                            OriginalPrice = 13380000m
                        },
                        new
                        {
                            Id = 18,
                            Content = "Mô tả chi tiết sản phẩm Baseus USB-C Hub. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4827),
                            Name = "Baseus USB-C Hub",
                            OriginalPrice = 18860000m,
                            SalePrice = 16031000.00m
                        },
                        new
                        {
                            Id = 19,
                            Content = "Mô tả chi tiết sản phẩm OPPO Find X7 Ultra. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4829),
                            Name = "OPPO Find X7 Ultra",
                            OriginalPrice = 41940000m
                        },
                        new
                        {
                            Id = 20,
                            Content = "Mô tả chi tiết sản phẩm Google Pixel 8 Pro. Sản phẩm chất lượng cao, bảo hành chính hãng.",
                            CreatedDate = new DateTime(2026, 3, 2, 12, 50, 29, 116, DateTimeKind.Local).AddTicks(4831),
                            Name = "Google Pixel 8 Pro",
                            OriginalPrice = 29100000m,
                            SalePrice = 24735000.00m
                        });
                });

            modelBuilder.Entity("Ecommerce.API.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 1
                        });
                });

            modelBuilder.Entity("Ecommerce.API.Entities.ProductCategory", b =>
                {
                    b.HasOne("Ecommerce.API.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.API.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.API.Entities.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Ecommerce.API.Entities.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
